### PR TITLE
correct App.js: import & use createMuiTheme

### PR DESCRIPTION
**Pull request by benedictjohannes**
`createTheme` is the new shiny export from `@material-ui/core/styles`

As of version 4.11 used in here, the import is still `createMuiTheme`, the new `createTheme` isn't supported as of this version. 

Either merge this change allowing the frontend to be built correctly, or upgrade the MUI dependency versions.

### CODE REVIEW

**Comment by fogolin** [comment]
I think it is the opposite, got a notification saying it should be reverted back.

**Comment by benedictjohannes** [comment]
> I think it is the opposite, got a notification saying it should be reverted back.

@fogolin notification from what, btw?

**Comment by benedictjohannes** [comment]
@fogolin I've change my merge comment. As the used MUI version is 4.11 as per package.json

**Comment by fogolin** [comment]
I get the notification in the console when using the frontend:

image

**Comment by benedictjohannes** [comment]
> I get the notification in the console when using the frontend:
> 
> image

You're most likely not using version **4.11.0** of Material UI in package.json. version 4.11.0 does not export `createMuiTheme`, causing build errors.

**Comment by fogolin** [comment]
```
"@material-ui/core": "^4.11.0",
"@material-ui/icons": "^4.9.1",
```

image


> > I get the notification in the console when using the frontend:
> > image
> 
> You're most likely not using version **4.11.0** of Material UI in package.json. version 4.11.0 does not export `createTheme`, causing build errors.

**Pull request closed without merging**
